ALTER TABLE stg.integration_source
ADD COLUMN IF NOT EXISTS poll_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS poll_interval_minutes INTEGER NOT NULL DEFAULT 30,
ADD COLUMN IF NOT EXISTS poll_window_start_local TIME NOT NULL DEFAULT TIME '10:30',
ADD COLUMN IF NOT EXISTS poll_window_end_local TIME NOT NULL DEFAULT TIME '00:00',
ADD COLUMN IF NOT EXISTS poll_timezone TEXT NOT NULL DEFAULT 'Europe/Istanbul';
