export function sellerCodeRequestReturnProjection(alias: string) {
  return `
            ${alias}.seller_code_request_id,
            ${alias}.company_id,
            ${alias}.region_id,
            ${alias}.store_id,
            s.store_code,
            s.store_name,
            ${alias}.store_type,
            ${alias}.request_type,
            ${alias}.request_status,
            ${alias}.first_name,
            ${alias}.last_name,
            ${alias}.national_id_hash,
            ${alias}.national_id_last4,
            ${alias}.phone_number,
            ${alias}.requested_hire_date,
            ${alias}.requested_position_id,
            p.position_code,
            p.position_name,
            ${alias}.employment_type,
            ${alias}.requested_seller_code,
            ${alias}.approved_seller_code,
            ${alias}.last_reference_seller_code,
            ${alias}.submitted_by_user_id,
            ${alias}.reviewed_by_user_id,
            ${alias}.reviewed_at,
            ${alias}.review_note,
            ${alias}.employee_id,
            ${alias}.created_at,
            ${alias}.updated_at`;
}

export function offboardingRequestReturnProjection(alias: string) {
  return `
            ${alias}.offboarding_request_id,
            ${alias}.company_id,
            ${alias}.region_id,
            ${alias}.store_id,
            s.store_code,
            s.store_name,
            ${alias}.employee_id,
            e.external_employee_ref,
            e.first_name,
            e.last_name,
            p.position_code,
            p.position_name,
            ${alias}.request_status,
            ${alias}.requested_termination_date,
            ${alias}.termination_reason,
            ${alias}.request_reason,
            ${alias}.submitted_by_user_id,
            ${alias}.reviewed_by_user_id,
            ${alias}.reviewed_at,
            ${alias}.review_note,
            ${alias}.created_at,
            ${alias}.updated_at`;
}
