import { mkdir, readFile, writeFile } from "node:fs/promises"
import { fileURLToPath } from "node:url"
import path from "node:path"

const pluginRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
await import("./generate-catalog-manifest.mjs")
const sourceFiles = [
  "src/bootstrap.js",
  "src/catalog-manifest.generated.js",
  "src/foundations.js",
  "src/components.js",
  "src/shadcn-components.js",
  "src/main.js",
]

const sources = await Promise.all(
  sourceFiles.map((file) => readFile(path.join(pluginRoot, file), "utf8")),
)

const banner = [
  "// Generated by scripts/build.mjs. Edit src/* and rebuild.",
  '"use strict";',
  "",
].join("\n")

await mkdir(path.join(pluginRoot, "dist"), { recursive: true })
await writeFile(
  path.join(pluginRoot, "dist/code.js"),
  `${banner}${sources.map((source) => source.trimEnd()).join("\n\n")}\n`,
  "utf8",
)
