import { demoStoreId, demoEmployeeId, regionSecondStoreId } from './store-surfaces-identities'

export const authSessionFixture = {
  authMode: 'mock',
  authenticated: true,
  user: {
    userId: 'store-me-smoke-user',
    employeeId: demoEmployeeId,
    roleCodes: ['STORE_PERSONNEL', 'STORE_MANAGER', 'offline_access', 'uma_authorization', 'default-roles-store-ops'],
    scope: {
      companyIds: ['00000000-0000-0000-0000-000000000001'],
      regionIds: ['00000000-0000-0000-0000-000000000010'],
      storeIds: [demoStoreId],
    },
    readScope: {
      companyIds: ['00000000-0000-0000-0000-000000000001'],
      regionIds: ['00000000-0000-0000-0000-000000000010'],
      storeIds: [demoStoreId],
    },
    actionScope: {
      assignedStoreIds: [demoStoreId],
      assignedStoreTypes: ['company'],
    },
    assignedStoreIds: [demoStoreId],
  },
  scopeSummary: {
    companyCount: 1,
    regionCount: 1,
    storeCount: 1,
    assignedStoreCount: 1,
  },
}

export const workflowInboxFixture = {
  items: [
    {
      itemType: 'task',
      sourceType: 'kpi_exception',
      sourceId: 'snapshot-2026-04-24:store:kpi',
      title: 'UPT at risk',
      summary: 'IstinyePark Demo Store icin KPI exception takibi gerekiyor',
      storeId: demoStoreId,
      storeName: 'IstinyePark Demo Store',
      workflowStatus: 'at_risk',
      inboxStatus: 'needs_attention',
      urgency: 'high',
      createdAt: '2026-04-24T08:00:00.000Z',
      needsAttentionAt: '2026-04-24T08:00:00.000Z',
      actorRole: 'STORE_MANAGER',
      primaryActionLabel: 'Open KPI detail',
      secondaryActionLabel: 'Detay aç',
      deepLink: '/store/kpis',
      historyPreview: 'Achievement 84%',
    },
  ],
  meta: {
    count: 1,
    total: 1,
    limit: 30,
    offset: 0,
  },
}

export const checklistAcknowledgementsFixture = {
  items: [
    {
      checklistInstanceId: 'checklist-instance-bm-1',
      checklistTemplateId: 'checklist-template-bm-1',
      templateName: 'BM Result',
      templateType: 'BM_STORE_VISIT',
      category: 'BM',
      storeId: demoStoreId,
      storeName: 'IstinyePark Demo Store',
      completedByUserId: 'region-user-1',
      completedAt: '2026-05-12T09:00:00.000Z',
      status: 'completed',
      totalScore: 82,
      complianceRate: 0.82,
      responses: [],
      acknowledgement: null,
    },
    {
      checklistInstanceId: 'checklist-instance-vm-1',
      checklistTemplateId: 'checklist-template-vm-1',
      templateName: 'VM Result',
      templateType: 'VM_STORE_VISIT',
      category: 'VM',
      storeId: demoStoreId,
      storeName: 'IstinyePark Demo Store',
      completedByUserId: 'vm-user-1',
      completedAt: '2026-05-11T09:00:00.000Z',
      status: 'completed',
      totalScore: 94,
      complianceRate: 0.94,
      responses: [],
      acknowledgement: {
        checklistAcknowledgementId: 'checklist-ack-vm-1',
        acknowledgedByUserId: 'store-manager-1',
        acknowledgementNote: 'Goruldu',
        acknowledgedAt: '2026-05-11T11:00:00.000Z',
      },
    },
  ],
  meta: {
    count: 2,
    total: 2,
    limit: 50,
    offset: 0,
  },
}

export const mobileChecklistTodayFixture = {
  data: {
    stores: [
      { storeId: demoStoreId, storeName: 'IstinyePark Demo Store' },
      { storeId: regionSecondStoreId, storeName: 'Marmara Park Demo Store' },
    ],
    templates: [
      {
        checklistTemplateId: 'checklist-template-bm-1',
        templateCode: 'BM_STORE_VISIT_2026',
        templateType: 'BM_STORE_VISIT',
        templateName: 'BM Visit',
        versionNo: 1,
        items: [],
      },
      {
        checklistTemplateId: 'checklist-template-vm-1',
        templateCode: 'VM_STORE_VISIT_2026',
        templateType: 'VM_STORE_VISIT',
        templateName: 'VM Visit',
        versionNo: 1,
        items: [],
      },
    ],
    activeInstances: [
      {
        checklistInstanceId: 'checklist-active-bm-1',
        checklistTemplateId: 'checklist-template-bm-1',
        storeId: demoStoreId,
        status: 'in_progress',
        startedAt: '2026-05-12T10:00:00.000Z',
        updatedAt: '2026-05-12T10:10:00.000Z',
        responses: [],
      },
    ],
    completedThisMonth: [
      {
        checklistInstanceId: 'checklist-instance-bm-1',
        checklistTemplateId: 'checklist-template-bm-1',
        storeId: demoStoreId,
        completedAt: '2026-05-12T09:00:00.000Z',
        totalScore: 82,
        acknowledgedAt: null,
      },
    ],
    pendingAcknowledgements: [],
    monthlySummaries: [
      {
        storeId: demoStoreId,
        checklistTemplateId: 'checklist-template-bm-1',
        monthStart: '2026-05-01',
        completedCount: 1,
        averageScore: 82,
      },
    ],
  },
}

export const storeFeedFixture = {
  items: [
    {
      feedPostId: 'store-home-feed-1',
      postType: 'announcement',
      title: 'Pilot announcement',
      body: 'Pilot store shell announcement.',
      linkLabel: null,
      linkUrl: null,
      visibilityScopeType: 'store',
      visibilityScopeIds: [demoStoreId],
      isPinned: true,
      publishStatus: 'published',
      publishedAt: '2026-05-01T08:00:00.000Z',
      startsAt: null,
      endsAt: null,
      metricCode: null,
      metricLabel: null,
      challengeStartsOn: null,
      challengeEndsOn: null,
      targetRoute: null,
      createdByUserId: 'store-me-smoke-user',
      updatedByUserId: 'store-me-smoke-user',
      createdAt: '2026-05-01T08:00:00.000Z',
      updatedAt: '2026-05-01T08:00:00.000Z',
    },
  ],
  meta: {
    count: 1,
    total: 1,
    limit: 50,
    offset: 0,
  },
}

export const kpiConfigFixture = {
  storeProfile: {
    profileCode: 'store',
    title: 'Store Score',
    summary: 'Store score profile',
    futureMetricRule: 'Manual review',
    metrics: [
      {
        code: 'TARGET_ACHIEVEMENT',
        label: 'Target Achievement',
        weightPercent: 70,
        ownerRole: 'STORE_MANAGER',
        scoreBehavior: 'score_only',
      },
      {
        code: 'UPT',
        label: 'Units Per Ticket',
        weightPercent: 30,
        ownerRole: 'STORE_MANAGER',
        scoreBehavior: 'score_only',
      },
    ],
  },
  personnelProfile: {
    profileCode: 'personnel',
    title: 'Personnel Score',
    summary: 'Personnel score profile',
    futureMetricRule: 'Manual review',
    metrics: [
      {
        code: 'TARGET_ACHIEVEMENT',
        label: 'Target Achievement',
        weightPercent: 40,
        ownerRole: 'STORE_PERSONNEL',
        scoreBehavior: 'score_only',
      },
      {
        code: 'ATV',
        label: 'Average Ticket Value',
        weightPercent: 30,
        ownerRole: 'STORE_PERSONNEL',
        scoreBehavior: 'score_only',
      },
      {
        code: 'UPT',
        label: 'Units Per Ticket',
        weightPercent: 30,
        ownerRole: 'STORE_PERSONNEL',
        scoreBehavior: 'score_only',
      },
    ],
  },
  ownershipMatrix: [],
  gradingBands: [
    {
      code: 'A',
      label: 'Excellent',
      emoji: 'A',
      tone: 'calm',
      minScore: 1,
    },
    {
      code: 'B',
      label: 'Healthy',
      emoji: 'B',
      tone: 'accent',
      minScore: 0.85,
    },
  ],
}

export const myPerformanceFixture = {
  source: {
    mode: 'live',
    snapshotRunId: null,
    snapshotDate: null,
  },
  employee: {
    employeeId: demoEmployeeId,
    displayName: 'Store Personnel',
    storeId: demoStoreId,
    storeName: 'IstinyePark Demo Store',
  },
  period: {
    periodStart: '2026-04-01',
    periodEnd: '2026-04-30',
  },
  score: {
    value: 91.5,
    matchedMetrics: 3,
    totalMetrics: 3,
  },
  rankings: {
    turkeyRank: 1,
    turkeyPopulation: 4,
    storeRank: 1,
    storePopulation: 3,
  },
  availablePeriods: [
    {
      periodType: 'monthly',
      periodStart: '2026-04-01',
      periodEnd: '2026-04-30',
    },
    {
      periodType: 'monthly',
      periodStart: '2026-05-01',
      periodEnd: '2026-05-31',
    },
  ],
  partial: {
    isPartial: false,
    missingMetricCodes: [],
    missingMetricLabels: [],
    pendingNormalizationCodes: [],
    pendingNormalizationLabels: [],
  },
  supporting: {
    netSalesValue: 145000,
    targetEntryMode: 'manager_assignment',
    targetEditableByCurrentUser: false,
  },
  metrics: [
    {
      code: 'TARGET_ACHIEVEMENT',
      label: 'Target Achievement',
      weightPercent: 40,
      actualValue: 0.98,
      targetValue: null,
      achievementRate: 0.98,
      contributionValue: 39.2,
      dataStatus: 'reported',
      scoreStatus: 'scored',
      status: 'reported',
    },
    {
      code: 'ATV',
      label: 'Average Ticket Value',
      weightPercent: 30,
      actualValue: 96,
      targetValue: null,
      achievementRate: 96,
      contributionValue: 28.8,
      dataStatus: 'reported',
      scoreStatus: 'scored',
      status: 'reported',
    },
    {
      code: 'UPT',
      label: 'Units Per Ticket',
      weightPercent: 30,
      actualValue: 95,
      targetValue: null,
      achievementRate: 95,
      contributionValue: 28.5,
      dataStatus: 'reported',
      scoreStatus: 'scored',
      status: 'reported',
    },
  ],
}

export const ownIncentivesFixture = {
  data: {
    period: '2026-06',
    periodStart: '2026-06-01',
    periodEnd: '2026-06-30',
    periodTimezone: 'Europe/Istanbul',
    roleScope: 'own',
    projections: [
      {
        period: '2026-06',
        periodTimezone: 'Europe/Istanbul',
        closeCutoffAt: null,
        ruleVersionId: 'sales-target-incentive-v1.0.0',
        storeId: demoStoreId,
        storeName: 'IstinyePark Demo Store',
        storeOwnershipType: 'company',
        roleScope: 'own',
        storeTarget: '1000000.00',
        storeActualNetSales: '1000000.00',
        storeAchievementPct: '100.0000',
        storeGatePassed: true,
        calculationState: 'projected',
        blockedReason: null,
        lastImportAt: '2026-06-18T08:00:00.000Z',
        rows: [
          {
            employeeId: demoEmployeeId,
            displayName: 'Store Personnel',
            participantType: 'personnel',
            positionCode: 'SALES_ASSOCIATE',
            normalizedFromPositionCode: null,
            target: '1000000.00',
            actualPositiveSales: '820000.00',
            achievementPct: '82.0000',
            storeAchievementPct: '100.0000',
            storeGatePassed: true,
            rate: '0.0150',
            rawEarnedAmount: '12300.000000',
            payableAmount: '12300.00',
            correctionAmount: null,
            adjustmentAmount: null,
            finalAmount: null,
            status: 'projected',
            blockedReason: null,
            rateTableVersion: 'personnel-sales-target-v1.0.0',
            explanation: 'Fixture projection.',
          },
        ],
      },
    ],
  },
}

export const storeIncentivesFixture = {
  data: {
    ...ownIncentivesFixture.data,
    roleScope: 'store',
    projections: [
      {
        ...ownIncentivesFixture.data.projections[0],
        roleScope: 'store',
        rows: [
          {
            employeeId: 'manager-1',
            displayName: 'Store Manager',
            participantType: 'store_manager',
            positionCode: 'STORE_MANAGER',
            normalizedFromPositionCode: null,
            target: '1000000.00',
            actualPositiveSales: '1500000.00',
            achievementPct: '150.0000',
            storeAchievementPct: '150.0000',
            storeGatePassed: null,
            rate: '0.0100',
            rawEarnedAmount: '15000.000000',
            payableAmount: '15000.00',
            correctionAmount: null,
            adjustmentAmount: null,
            finalAmount: null,
            status: 'projected',
            blockedReason: null,
            rateTableVersion: 'manager-sales-target-v1.0.0',
            explanation: 'Fixture projection.',
          },
          {
            ...ownIncentivesFixture.data.projections[0].rows[0],
            actualPositiveSales: '1000000.00',
            achievementPct: '100.0000',
            rawEarnedAmount: '16500.000000',
            payableAmount: '16500.00',
            rate: '0.0165',
          },
        ],
      },
    ],
  },
}

export const myPerformanceMayFixture = {
  ...myPerformanceFixture,
  period: {
    periodStart: '2026-05-01',
    periodEnd: '2026-05-31',
  },
  score: {
    value: 93.2,
    matchedMetrics: 3,
    totalMetrics: 3,
  },
  rankings: {
    turkeyRank: 1,
    turkeyPopulation: 4,
    storeRank: 1,
    storePopulation: 3,
  },
  supporting: {
    netSalesValue: 172000,
    targetEntryMode: 'manager_assignment',
    targetEditableByCurrentUser: false,
  },
  metrics: [
    {
      code: 'TARGET_ACHIEVEMENT',
      label: 'Target Achievement',
      weightPercent: 40,
      actualValue: 1.04,
      targetValue: null,
      achievementRate: 1.04,
      contributionValue: 41.6,
      dataStatus: 'reported',
      scoreStatus: 'scored',
      status: 'reported',
    },
    {
      code: 'ATV',
      label: 'Average Ticket Value',
      weightPercent: 30,
      actualValue: 112,
      targetValue: null,
      achievementRate: 112,
      contributionValue: 33.6,
      dataStatus: 'reported',
      scoreStatus: 'scored',
      status: 'reported',
    },
    {
      code: 'UPT',
      label: 'Units Per Ticket',
      weightPercent: 30,
      actualValue: 101,
      targetValue: null,
      achievementRate: 101,
      contributionValue: 30.3,
      dataStatus: 'reported',
      scoreStatus: 'scored',
      status: 'reported',
    },
  ],
}
