import { lazy } from 'react'

const loadAuditCenterPage = () => import('../pages/AuditCenterPage').then((module) => ({ default: module.AuditCenterPage }))
const loadAdminFeedPage = () => import('../pages/AdminFeedPage').then((module) => ({ default: module.AdminFeedPage }))
const loadAdminChecklistTemplatesPage = () => import('../pages/AdminChecklistTemplatesPage').then((module) => ({ default: module.AdminChecklistTemplatesPage }))
const loadAdminKpiConfigPage = () => import('../pages/AdminKpiConfigPage').then((module) => ({ default: module.AdminKpiConfigPage }))
const loadAdminPilotFeedbackPage = () => import('../pages/AdminPilotFeedbackPage').then((module) => ({ default: module.AdminPilotFeedbackPage }))
const loadAdminInboxPage = () => import('../pages/AdminInboxPage').then((module) => ({ default: module.AdminInboxPage }))
const loadAdminDataQualityCenterPage = () => import('../pages/AdminDataQualityCenterPage').then((module) => ({ default: module.AdminDataQualityCenterPage }))
const loadAuthActionStoreAssignmentAuditPage = () => import('../pages/AuthActionStoreAssignmentAuditPage').then((module) => ({ default: module.AuthActionStoreAssignmentAuditPage }))
const loadAuthAssignmentAuditPage = () => import('../pages/AuthAssignmentAuditPage').then((module) => ({ default: module.AuthAssignmentAuditPage }))
const loadAuthCallbackPage = () => import('../pages/AuthCallbackPage').then((module) => ({ default: module.AuthCallbackPage }))
const loadAuthCatalogPage = () => import('../pages/AuthCatalogPage').then((module) => ({ default: module.AuthCatalogPage }))
const loadAuthDashboardPage = () => import('../pages/AuthDashboardPage').then((module) => ({ default: module.AuthDashboardPage }))
const loadAuthLoginPage = () => import('../pages/AuthLoginPage').then((module) => ({ default: module.AuthLoginPage }))
const loadAuthLogoutPage = () => import('../pages/AuthLogoutPage').then((module) => ({ default: module.AuthLogoutPage }))
const loadAuthUserAuditPage = () => import('../pages/AuthUserAuditPage').then((module) => ({ default: module.AuthUserAuditPage }))
const loadCompetitionDashboardPage = () => import('../pages/CompetitionDashboardPage').then((module) => ({ default: module.CompetitionDashboardPage }))
const loadImportBatchDetailPage = () => import('../pages/ImportBatchDetailPage').then((module) => ({ default: module.ImportBatchDetailPage }))
const loadIntegrationDashboardPage = () => import('../pages/IntegrationDashboardPage').then((module) => ({ default: module.IntegrationDashboardPage }))
const loadMasterDataBootstrapPage = () => import('../pages/MasterDataBootstrapPage').then((module) => ({ default: module.MasterDataBootstrapPage }))
const loadOperationsControlTowerPage = () => import('../pages/OperationsControlTowerPage').then((module) => ({ default: module.OperationsControlTowerPage }))
const loadReportsChecklistsPage = () => import('../pages/ReportsChecklistsPage').then((module) => ({ default: module.ReportsChecklistsPage }))
const loadReportsKpisPage = () => import('../pages/ReportsKpisPage').then((module) => ({ default: module.ReportsKpisPage }))
const loadReportsSnapshotRunsPage = () => import('../pages/ReportsSnapshotRunsPage').then((module) => ({ default: module.ReportsSnapshotRunsPage }))
const loadReportsSummaryPage = () => import('../pages/ReportsSummaryPage').then((module) => ({ default: module.ReportsSummaryPage }))
const loadReportsTurnoverPage = () => import('../pages/ReportsTurnoverPage').then((module) => ({ default: module.ReportsTurnoverPage }))
const loadReportsWorkforcePage = () => import('../pages/ReportsWorkforcePage').then((module) => ({ default: module.ReportsWorkforcePage }))
const loadSessionReadinessPage = () => import('../pages/SessionReadinessPage').then((module) => ({ default: module.SessionReadinessPage }))
const loadSnapshotRunDetailPage = () => import('../pages/SnapshotRunDetailPage').then((module) => ({ default: module.SnapshotRunDetailPage }))
const loadSnapshotsDashboardPage = () => import('../pages/SnapshotsDashboardPage').then((module) => ({ default: module.SnapshotsDashboardPage }))
const loadStoreApprovalsPage = () => import('../pages/StoreApprovalsPage').then((module) => ({ default: module.StoreApprovalsPage }))
const loadStoreChecklistsPage = () => import('../pages/StoreChecklistsPage').then((module) => ({ default: module.StoreChecklistsPage }))
const loadStoreCompetitionsPage = () => import('../pages/StoreCompetitionsPage').then((module) => ({ default: module.StoreCompetitionsPage }))
const loadStoreFeedPage = () => import('../pages/StoreFeedPage').then((module) => ({ default: module.StoreFeedPage }))
const loadStoreHomePage = () => import('../pages/StoreHomePage').then((module) => ({ default: module.StoreHomePage }))
const loadStoreIncentivesPage = () => import('../pages/StoreIncentivesPage').then((module) => ({ default: module.StoreIncentivesPage }))
const loadStoreKpiHighlightsPage = () => import('../pages/StoreKpiHighlightsPage').then((module) => ({ default: module.StoreKpiHighlightsPage }))
const loadStoreMyPerformancePage = () => import('../pages/StoreMyPerformancePage').then((module) => ({ default: module.StoreMyPerformancePage }))
const loadStorePersonnelPerformancePage = () => import('../pages/StorePersonnelPerformancePage').then((module) => ({ default: module.StorePersonnelPerformancePage }))
const loadStoreRankingsPage = () => import('../pages/StoreRankingsPage').then((module) => ({ default: module.StoreRankingsPage }))
const loadStoreReportsPage = () => import('../pages/StoreReportsPage').then((module) => ({ default: module.StoreReportsPage }))
const loadStoreSettingsPage = () => import('../pages/StoreSettingsPage').then((module) => ({ default: module.StoreSettingsPage }))
const loadStoreTargetsPage = () => import('../pages/StoreTargetsPage').then((module) => ({ default: module.StoreTargetsPage }))
const loadStoreTasksPage = () => import('../pages/StoreTasksPage').then((module) => ({ default: module.StoreTasksPage }))
const loadTargetApprovalQueuePage = () => import('../pages/TargetApprovalQueuePage').then((module) => ({ default: module.TargetApprovalQueuePage }))

export const AuditCenterPage = lazy(loadAuditCenterPage)
export const AdminFeedPage = lazy(loadAdminFeedPage)
export const AdminChecklistTemplatesPage = lazy(loadAdminChecklistTemplatesPage)
export const AdminKpiConfigPage = lazy(loadAdminKpiConfigPage)
export const AdminPilotFeedbackPage = lazy(loadAdminPilotFeedbackPage)
export const AdminInboxPage = lazy(loadAdminInboxPage)
export const AdminDataQualityCenterPage = lazy(loadAdminDataQualityCenterPage)
export const AuthActionStoreAssignmentAuditPage = lazy(loadAuthActionStoreAssignmentAuditPage)
export const AuthAssignmentAuditPage = lazy(loadAuthAssignmentAuditPage)
export const AuthCallbackPage = lazy(loadAuthCallbackPage)
export const AuthCatalogPage = lazy(loadAuthCatalogPage)
export const AuthDashboardPage = lazy(loadAuthDashboardPage)
export const AuthLoginPage = lazy(loadAuthLoginPage)
export const AuthLogoutPage = lazy(loadAuthLogoutPage)
export const AuthUserAuditPage = lazy(loadAuthUserAuditPage)
export const CompetitionDashboardPage = lazy(loadCompetitionDashboardPage)
export const ImportBatchDetailPage = lazy(loadImportBatchDetailPage)
export const IntegrationDashboardPage = lazy(loadIntegrationDashboardPage)
export const MasterDataBootstrapPage = lazy(loadMasterDataBootstrapPage)
export const OperationsControlTowerPage = lazy(loadOperationsControlTowerPage)
export const ReportsChecklistsPage = lazy(loadReportsChecklistsPage)
export const ReportsKpisPage = lazy(loadReportsKpisPage)
export const ReportsSnapshotRunsPage = lazy(loadReportsSnapshotRunsPage)
export const ReportsSummaryPage = lazy(loadReportsSummaryPage)
export const ReportsTurnoverPage = lazy(loadReportsTurnoverPage)
export const ReportsWorkforcePage = lazy(loadReportsWorkforcePage)
export const SessionReadinessPage = lazy(loadSessionReadinessPage)
export const SnapshotRunDetailPage = lazy(loadSnapshotRunDetailPage)
export const SnapshotsDashboardPage = lazy(loadSnapshotsDashboardPage)
export const StoreApprovalsPage = lazy(loadStoreApprovalsPage)
export const StoreChecklistsPage = lazy(loadStoreChecklistsPage)
export const StoreCompetitionsPage = lazy(loadStoreCompetitionsPage)
export const StoreFeedPage = lazy(loadStoreFeedPage)
export const StoreHomePage = lazy(loadStoreHomePage)
export const StoreIncentivesPage = lazy(loadStoreIncentivesPage)
export const StoreKpiHighlightsPage = lazy(loadStoreKpiHighlightsPage)
export const StoreMyPerformancePage = lazy(loadStoreMyPerformancePage)
export const StorePersonnelPerformancePage = lazy(loadStorePersonnelPerformancePage)
export const StoreRankingsPage = lazy(loadStoreRankingsPage)
export const StoreReportsPage = lazy(loadStoreReportsPage)
export const StoreSettingsPage = lazy(loadStoreSettingsPage)
export const StoreTargetsPage = lazy(loadStoreTargetsPage)
export const StoreTasksPage = lazy(loadStoreTasksPage)
export const TargetApprovalQueuePage = lazy(loadTargetApprovalQueuePage)
