parent=keycloak
import=common/keycloak
styles=css/login-studio.css css/keycloak-form.css
stylesCommon=
locales=tr
kcFormGroupClass=field-block
kcLabelClass=axis-label
kcInputClass=axis-input
kcInputGroup=password-wrap
kcInputErrorMessageClass=field-error
kcFormSettingClass=form-options
kcFormPasswordVisibilityButtonClass=password-toggle
kcFormPasswordVisibilityIconShow=axis-eye
kcFormPasswordVisibilityIconHide=axis-eye-off
kcButtonClass=axis-button
kcButtonPrimaryClass=axis-primary
kcButtonDefaultClass=axis-secondary
kcFormButtonsClass=axis-form-buttons
