import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ArrowLeft } from 'lucide-react'
import { Link } from 'react-router-dom'
import { EmptyState, KeyValue, ScreenState, StatusPill } from '../components/dashboard-primitives'
import { ReportingToolbar } from '../components/reporting-tools'
import { getReportingSnapshotRuns } from '../features/reports/api'
import { downloadCsv } from '../lib/download-csv'
import { formatDate, formatDateTime, getErrorMessage, mapHealthTone } from '../lib/format'

export function ReportsSnapshotRunsPage() {
  const [sortBy, setSortBy] = useState<'generated-desc' | 'generated-asc' | 'type'>('generated-desc')
  const runsQuery = useQuery({
    queryKey: ['reporting-snapshot-runs-page'],
    queryFn: () => getReportingSnapshotRuns(),
  })
  const runs = useMemo(() => runsQuery.data?.items ?? [], [runsQuery.data?.items])
  const sortedRuns = useMemo(() => {
    const items = [...runs]
    if (sortBy === 'generated-asc') {
      return items.sort((left, right) => left.generatedAt.localeCompare(right.generatedAt))
    }
    if (sortBy === 'type') {
      return items.sort((left, right) => left.snapshotType.localeCompare(right.snapshotType))
    }
    return items.sort((left, right) => right.generatedAt.localeCompare(left.generatedAt))
  }, [runs, sortBy])

  if (runsQuery.isLoading) {
    return <ScreenState title="Loading report snapshot runs" copy="Pulling recent reporting contexts." />
  }

  if (runsQuery.isError) {
    return <ScreenState title="Snapshot runs unavailable" copy={getErrorMessage(runsQuery.error)} tone="error" />
  }

  return (
    <section className="page-stack">
      <section className="hero-panel">
        <div>
          <div className="eyebrow">Reporting Drill-Down</div>
          <h2 className="hero-title">Choose the reporting snapshot before you read the rows.</h2>
          <p className="hero-copy">
            Reporting is anchored to immutable snapshot runs. This list gives us stable contexts for
            workforce, KPI, checklist, and turnover drill-down pages.
          </p>
        </div>
        <Link className="back-link" to="/admin/reports">
          <ArrowLeft size={16} />
          <span>Back to reporting summary</span>
        </Link>
      </section>

      <section className="panel">
        <div className="panel-heading panel-heading-spread">
          <div>
            <div className="eyebrow">Snapshot contexts</div>
            <h3>Recent reporting runs</h3>
          </div>
          <ReportingToolbar
            sortValue={sortBy}
            onSortChange={(value) => setSortBy(value as typeof sortBy)}
            sortOptions={[
              { value: 'generated-desc', label: 'Newest first' },
              { value: 'generated-asc', label: 'Oldest first' },
              { value: 'type', label: 'Snapshot type' },
            ]}
            onExport={() =>
              downloadCsv({
                filename: 'reporting-snapshot-runs.csv',
                columns: ['snapshotRunId', 'snapshotType', 'runStatus', 'snapshotDate', 'periodStart', 'periodEnd', 'generatedAt', 'generatedBy'],
                rows: sortedRuns.map((run) => [
                  run.snapshotRunId,
                  run.snapshotType,
                  run.runStatus,
                  run.snapshotDate,
                  run.periodStart,
                  run.periodEnd,
                  run.generatedAt,
                  run.generatedBy,
                ]),
              })
            }
          />
        </div>

        {sortedRuns.length === 0 ? (
          <EmptyState copy="No reporting snapshot runs are available yet." />
        ) : (
          <div className="stacked-table">
            {sortedRuns.map((run) => (
              <article className="stacked-row" key={run.snapshotRunId}>
                <div className="stacked-row-head">
                  <div>
                    <strong>{run.snapshotType} snapshot</strong>
                    <span className="queue-subtitle">{run.snapshotRunId}</span>
                  </div>
                  <StatusPill tone={mapHealthTone(run.runStatus)}>{run.runStatus}</StatusPill>
                </div>

                <div className="key-grid">
                  <KeyValue label="Snapshot date" value={formatDate(run.snapshotDate)} />
                  <KeyValue label="Generated at" value={formatDateTime(run.generatedAt)} />
                  <KeyValue label="Period" value={`${formatDate(run.periodStart)} - ${formatDate(run.periodEnd)}`} />
                  <KeyValue label="Generated by" value={run.generatedBy} />
                </div>

                <div className="action-cluster">
                  <Link className="back-link" to={`/admin/reports/workforce/${run.snapshotRunId}`}>
                    <span>Open workforce</span>
                  </Link>
                  <Link className="back-link" to={`/admin/reports/kpis/${run.snapshotRunId}`}>
                    <span>Open KPIs</span>
                  </Link>
                  <Link className="back-link" to={`/admin/reports/checklists/${run.snapshotRunId}`}>
                    <span>Open checklists</span>
                  </Link>
                  <Link className="back-link" to={`/admin/reports/turnover/${run.snapshotRunId}`}>
                    <span>Open turnover</span>
                  </Link>
                </div>
              </article>
            ))}
          </div>
        )}
      </section>
    </section>
  )
}
